package com.virtualbeehive.expensekeeper;

import android.app.*;import android.os.*;import android.content.*;import android.provider.MediaStore;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import android.graphics.Color;import android.graphics.Typeface;import android.net.Uri;import java.text.*;import java.util.*;import org.json.*;

public class MainActivity extends Activity{
 int honey=Color.rgb(245,181,45),dark=Color.rgb(18,15,11),card=Color.rgb(38,32,24); LinearLayout root,content; SharedPreferences sp; String current="Dashboard";
 String[] categories={"Advertising & Marketing","AI Tools Subscriptions","Software & Subscriptions","Website / App Development","Office Supplies","Computer / Equipment","Phone & Internet","Travel","Business Meals","Vehicle / Mileage","Professional Fees","Bank / Payment Processing Fees","Rent / Office / Coworking","Insurance","Postage & Shipping","Training / Education","Licenses / Permits / Filing Fees","Contract Labor","Payroll / Wages","Taxes","Repairs & Maintenance","Other Business Expense"};
 @Override public void onCreate(Bundle b){super.onCreate(b); sp=getSharedPreferences("vb",0); showDashboard();}
 TextView tv(String t,int size,int color,int style){ TextView v=new TextView(this);v.setText(t);v.setTextSize(size);v.setTextColor(color);v.setTypeface(Typeface.DEFAULT,style);v.setPadding(10,6,10,6);return v;}
 Button btn(String t){ Button b=new Button(this);b.setText(t);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setBackgroundColor(honey);return b;}
 EditText input(String hint){ EditText e=new EditText(this);e.setHint(hint);e.setTextColor(Color.WHITE);e.setHintTextColor(Color.LTGRAY);e.setSingleLine(false);return e;}
 void base(String title){ ScrollView sv=new ScrollView(this); root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setPadding(22,22,22,22);root.setBackgroundColor(dark); sv.addView(root); LinearLayout head=new LinearLayout(this);head.setGravity(Gravity.CENTER_VERTICAL); ImageView logo=new ImageView(this);logo.setImageResource(getResources().getIdentifier("vb_logo","drawable",getPackageName())); head.addView(logo,new LinearLayout.LayoutParams(72,72)); LinearLayout htxt=new LinearLayout(this);htxt.setOrientation(LinearLayout.VERTICAL); htxt.addView(tv("VB Expense Keeper",22,honey,Typeface.BOLD)); htxt.addView(tv("Virtual Beehive Inc. private bookkeeping app",12,Color.LTGRAY,Typeface.NORMAL)); head.addView(htxt); root.addView(head); root.addView(tv(title,26,Color.WHITE,Typeface.BOLD)); content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL); root.addView(content); nav(); setContentView(sv);}
 void nav(){ LinearLayout n=new LinearLayout(this);n.setOrientation(LinearLayout.HORIZONTAL); String[] items={"Dashboard","Add","Profile","Records"}; for(String it:items){Button b=btn(it); b.setOnClickListener(v->{if(it.equals("Dashboard"))showDashboard();if(it.equals("Add"))showAdd();if(it.equals("Profile"))showProfile();if(it.equals("Records"))showRecords();}); n.addView(b,new LinearLayout.LayoutParams(0,90,1));} root.addView(n);}
 void card(String title,String body){ LinearLayout c=new LinearLayout(this);c.setOrientation(LinearLayout.VERTICAL);c.setPadding(18,18,18,18);c.setBackgroundColor(card); c.addView(tv(title,18,honey,Typeface.BOLD)); c.addView(tv(body,14,Color.WHITE,Typeface.NORMAL)); LinearLayout.LayoutParams lp=new LinearLayout.LayoutParams(-1,-2);lp.setMargins(0,12,0,12);content.addView(c,lp);}
 public void showDashboard(){base("Dashboard"); JSONArray arr=getRecords(); card("This Year",arr.length()+" recorded expense(s) stored locally on this phone."); card("Bookkeeping Rules","No expense can be deleted from the record list. If a mistake happens, add a correction note later. Google Drive/Sheets connection is the next version after APK testing."); Button add=btn("+ Add New Expense");add.setOnClickListener(v->showAdd());content.addView(add,new LinearLayout.LayoutParams(-1,100));}
 public void showProfile(){base("Profile"); EditText name=input("Full name");name.setText(sp.getString("name","Daniel Pirooz")); EditText pos=input("Position");pos.setText(sp.getString("position","CEO / Founder")); EditText email=input("Email");email.setText(sp.getString("email","danny@virtualbeehiveinc.com")); Button photo=btn("Choose Profile Picture"); photo.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_PICK, MediaStore.Images.Media.EXTERNAL_CONTENT_URI); startActivityForResult(i,55);}); Button save=btn("Save Profile"); save.setOnClickListener(v->{sp.edit().putString("name",name.getText().toString()).putString("position",pos.getText().toString()).putString("email",email.getText().toString()).apply(); Toast.makeText(this,"Profile saved",Toast.LENGTH_LONG).show();}); content.addView(tv("User profile is auto-added to every expense.",15,Color.LTGRAY,Typeface.NORMAL)); content.addView(name);content.addView(pos);content.addView(email);content.addView(photo);content.addView(save);}
 public void showAdd(){base("Add Expense"); Spinner cat=new Spinner(this); ArrayAdapter<String> ca=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,categories);cat.setAdapter(ca); Spinner freq=new Spinner(this); freq.setAdapter(new ArrayAdapter<String>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"One-time","Monthly recurring","Yearly recurring"})); EditText amount=input("Amount, e.g. 49.99"); EditText title=input("Expense title"); EditText desc=input("Description / business purpose"); EditText vendor=input("Vendor / store"); Button receipt=btn("Take Photo or Attach Receipt"); receipt.setOnClickListener(v->{Intent i=new Intent(Intent.ACTION_GET_CONTENT);i.setType("image/*");startActivityForResult(Intent.createChooser(i,"Select receipt"),77);}); Button scan=btn("Simulate AI Scan"); scan.setOnClickListener(v->{vendor.setText("Detected Vendor");amount.setText("49.99");title.setText("AI tool subscription");desc.setText("Business software / AI productivity expense for Virtual Beehive Inc.");cat.setSelection(1);}); Button save=btn("Record Expense"); save.setOnClickListener(v->{String ref="VB-"+new SimpleDateFormat("yyyy",Locale.US).format(new Date())+"-"+String.format(Locale.US,"%06d",getRecords().length()+1); JSONObject o=new JSONObject(); try{o.put("ref",ref);o.put("date",new SimpleDateFormat("yyyy-MM-dd HH:mm",Locale.US).format(new Date()));o.put("by",sp.getString("name","Daniel Pirooz"));o.put("position",sp.getString("position","CEO / Founder"));o.put("category",cat.getSelectedItem().toString());o.put("frequency",freq.getSelectedItem().toString());o.put("amount",amount.getText().toString());o.put("title",title.getText().toString());o.put("description",desc.getText().toString());o.put("vendor",vendor.getText().toString());}catch(Exception e){} JSONArray a=getRecords();a.put(o);sp.edit().putString("records",a.toString()).apply(); new AlertDialog.Builder(this).setTitle("Expense recorded successfully").setMessage("Reference Number: "+ref).setPositiveButton("OK",(d,w)->showDashboard()).show();}); content.addView(tv("Category",14,honey,Typeface.BOLD));content.addView(cat);content.addView(tv("Frequency",14,honey,Typeface.BOLD));content.addView(freq);content.addView(amount);content.addView(title);content.addView(desc);content.addView(vendor);content.addView(receipt);content.addView(scan);content.addView(save,new LinearLayout.LayoutParams(-1,110));}
 public void showRecords(){base("Records"); JSONArray a=getRecords(); if(a.length()==0){card("No records yet","Add your first company expense.");return;} for(int i=a.length()-1;i>=0;i--){try{JSONObject o=a.getJSONObject(i);card(o.getString("ref"),o.optString("date")+"\n"+o.optString("category")+" | "+o.optString("frequency")+"\n$"+o.optString("amount")+" - "+o.optString("title")+"\nEntered by: "+o.optString("by"));}catch(Exception e){}}}
 JSONArray getRecords(){try{return new JSONArray(sp.getString("records","[]"));}catch(Exception e){return new JSONArray();}}
}
